[font]
#normal = { family = "Ubuntu", style = "Regular"}
size = 12
offset = { x = 1, y = 1}
#[font.normal]
#family = "Inter"
#style = "Regular"

[colors.primary]
background = "#1e1e1e"
foreground = "#ffffff"

[colors.bright]
black = "0x3e4452"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.normal]
black = "0x2c323c"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x5c6370"
yellow = "0xe5c07b"

